Diagnostics:
  # cofig for clang-tidy
  ClangTidy:
    Add:
      - bugprone-*
      - clang-analyzer-*
      - google-*
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
      - cppcoreguidelines-*
      - hicpp-*
      - misc-*

    Remove:
      - modernize-use-trailing-return-type
      - readability-magic-numbers
      - altera-unroll-loops
      - altera-id-dependent-backward-branch
      - cppcoreguidelines-slicing
      - cppcoreguidelines-narrowing-conversions
      - cppcoreguidelines-avoid-magic-numbers
      - cppcoreguidelines-avoid-c-arrays
      - cppcoreguidelines-pro-bounds-array-to-pointer-decay
      - cppcoreguidelines-pro-type-reinterpret-cast
      - cppcoreguidelines-pro-type-union-access
      - cppcoreguidelines-pro-type-const-cast
      - cppcoreguidelines-pro-bounds-pointer-arithmetic
      - cppcoreguidelines-pro-bounds-constant-array-index
      - cppcoreguidelines-avoid-const-or-ref-data-members
      - llvmlibc-restrict-system-libc-headers
      - bugprone-easily-swappable-parameters
      - bugprone-sizeof-expression
      - bugprone-narrowing-conversions
      - hicpp-no-array-decay
      - readability-identifier-length
      - hicpp-avoid-c-arrays
      - llvmlibc-implementation-in-namespace
      - llvmlibc-callee-namespace
      - google-runtime-int
      - llvmlibc-inline-function-decl
    CheckOptions:
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.EnumCase: CamelCase
      readability-identifier-naming.FunctionCase: CamelCase
      readability-identifier-naming.GlobalConstantCase: UPPER_CASE
      readability-identifier-naming.MemberCase: CamelCase
#     readability-identifier-naming.MemberPrefix:
      readability-identifier-naming.NamespaceCase: lower_case
      readability-identifier-naming.StructCase: CamelCase
      readability-identifier-naming.UnionCase: CamelCase
      readability-identifier-naming.VariableCase: lower_case

  # strictly check for useless header files
  UnusedIncludes: Strict